name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - osx_image: xcode10.2
            env: SWIFT=5.0 BUILD_SDK=iphonesimulator12.2 DESTINATION="platform=iOS Simulator,name=iPhone 8"
          - osx_image: xcode10.2
            env: SWIFT=4.3 BUILD_SDK=iphonesimulator12.2 DESTINATION="platform=iOS Simulator,name=iPhone 8"
          - osx_image: xcode10.1
            env: SWIFT=4.2 BUILD_SDK=iphonesimulator12.1 DESTINATION="platform=iOS Simulator,name=iPhone 8"
          - osx_image: xcode9.2
            env: SWIFT=4.0 BUILD_SDK=iphonesimulator11.2 DESTINATION="platform=iOS Simulator,name=iPhone 8"
          - osx_image: xcode9.4
            env: SWIFT=4.1 BUILD_SDK=iphonesimulator11.4 DESTINATION="platform=iOS Simulator,name=iPhone 8"
          - osx_image: xcode9.4
            env: SWIFT=3.3 BUILD_SDK=iphonesimulator11.4 DESTINATION="platform=iOS Simulator,name=iPhone 8"
          - osx_image: xcode8.3
            env: SWIFT=3.1 BUILD_SDK=iphonesimulator10.3 DESTINATION="platform=iOS Simulator,name=iPhone 7"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1 # Sets ruby version via `.ruby-version`
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install bundler
        run: gem install bundler
      - name: Run rake ci
        run: bundle exec rake ci

